-- Create recipes table
CREATE TABLE IF NOT EXISTS public.recipes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  cuisine TEXT NOT NULL,
  rating NUMERIC(3,1) NOT NULL DEFAULT 5.0,
  total_time INTEGER NOT NULL,
  prep_time INTEGER NOT NULL,
  cook_time INTEGER NOT NULL,
  description TEXT NOT NULL,
  serves INTEGER NOT NULL,
  ingredients JSONB DEFAULT '[]'::jsonb,
  instructions JSONB DEFAULT '[]'::jsonb,
  nutrients JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_recipes_cuisine ON public.recipes(cuisine);
CREATE INDEX IF NOT EXISTS idx_recipes_rating ON public.recipes(rating DESC);
CREATE INDEX IF NOT EXISTS idx_recipes_total_time ON public.recipes(total_time);
CREATE INDEX IF NOT EXISTS idx_recipes_created_at ON public.recipes(created_at DESC);

-- Insert sample recipe data
INSERT INTO public.recipes (title, cuisine, rating, total_time, prep_time, cook_time, description, serves, ingredients, instructions, nutrients) VALUES
('Spaghetti Carbonara', 'Italian', 4.8, 30, 10, 20, 'Classic Italian pasta with creamy egg sauce and crispy bacon', 4, '[{"name":"Spaghetti","amount":"400g"},{"name":"Eggs","amount":"4"},{"name":"Bacon","amount":"200g"},{"name":"Parmesan","amount":"100g"},{"name":"Salt","amount":"to taste"}]', '[{"step":1,"instruction":"Cook spaghetti in boiling salted water"},{"step":2,"instruction":"Fry bacon until crispy"},{"step":3,"instruction":"Mix eggs with grated parmesan"},{"step":4,"instruction":"Toss hot pasta with bacon and egg mixture"}]', '{"calories":450,"protein":"18g","carbs":"45g","fat":"20g"}'),
('Chicken Tikka Masala', 'Indian', 4.7, 45, 20, 25, 'Tender chicken in a rich and creamy tomato-based sauce with aromatic spices', 4, '[{"name":"Chicken Breast","amount":"600g"},{"name":"Yogurt","amount":"200ml"},{"name":"Tomato Sauce","amount":"400ml"},{"name":"Onions","amount":"2"},{"name":"Garlic","amount":"4 cloves"},{"name":"Ginger","amount":"1 inch"}]', '[{"step":1,"instruction":"Marinate chicken in yogurt and spices"},{"step":2,"instruction":"Cook chicken until golden"},{"step":3,"instruction":"Prepare sauce with tomatoes and cream"},{"step":4,"instruction":"Combine chicken with sauce and simmer"}]', '{"calories":380,"protein":"35g","carbs":"15g","fat":"18g"}'),
('Pad Thai', 'Thai', 4.6, 25, 10, 15, 'Stir-fried noodles with shrimp, tofu, and peanuts in a tangy sauce', 2, '[{"name":"Rice Noodles","amount":"300g"},{"name":"Shrimp","amount":"200g"},{"name":"Eggs","amount":"2"},{"name":"Peanuts","amount":"50g"},{"name":"Lime","amount":"1"},{"name":"Tamarind Paste","amount":"2 tbsp"}]', '[{"step":1,"instruction":"Soak rice noodles"},{"step":2,"instruction":"Heat wok and cook shrimp"},{"step":3,"instruction":"Add noodles and vegetables"},{"step":4,"instruction":"Toss with tamarind sauce"}]', '{"calories":420,"protein":"22g","carbs":"52g","fat":"14g"}'),
('Beef Tacos', 'Mexican', 4.5, 20, 5, 15, 'Seasoned ground beef in warm tortillas with fresh toppings', 4, '[{"name":"Ground Beef","amount":"500g"},{"name":"Tortillas","amount":"8"},{"name":"Lettuce","amount":"1 head"},{"name":"Tomato","amount":"2"},{"name":"Cheese","amount":"200g"},{"name":"Salsa","amount":"1 cup"}]', '[{"step":1,"instruction":"Brown ground beef with spices"},{"step":2,"instruction":"Warm tortillas"},{"step":3,"instruction":"Chop vegetables"},{"step":4,"instruction":"Assemble tacos with toppings"}]', '{"calories":380,"protein":"25g","carbs":"35g","fat":"16g"}'),
('Caesar Salad', 'Italian', 4.4, 15, 15, 0, 'Crisp romaine lettuce with creamy Caesar dressing and parmesan cheese', 2, '[{"name":"Romaine Lettuce","amount":"1 head"},{"name":"Parmesan","amount":"100g"},{"name":"Croutons","amount":"100g"},{"name":"Caesar Dressing","amount":"150ml"},{"name":"Lemon","amount":"1"}]', '[{"step":1,"instruction":"Wash and chop romaine"},{"step":2,"instruction":"Prepare Caesar dressing"},{"step":3,"instruction":"Toss salad with dressing"},{"step":4,"instruction":"Top with croutons and parmesan"}]', '{"calories":320,"protein":"12g","carbs":"18g","fat":"22g"}'),
('Risotto al Funghi', 'Italian', 4.7, 35, 10, 25, 'Creamy rice dish with mushrooms, white wine, and parmesan', 4, '[{"name":"Arborio Rice","amount":"300g"},{"name":"Mushrooms","amount":"400g"},{"name":"White Wine","amount":"200ml"},{"name":"Vegetable Stock","amount":"1L"},{"name":"Onion","amount":"1"},{"name":"Parmesan","amount":"100g"}]', '[{"step":1,"instruction":"Sauté mushrooms and set aside"},{"step":2,"instruction":"Cook onions in butter"},{"step":3,"instruction":"Add rice and toast"},{"step":4,"instruction":"Add stock gradually while stirring"},{"step":5,"instruction":"Finish with mushrooms and parmesan"}]', '{"calories":420,"protein":"14g","carbs":"52g","fat":"18g"}'),
('Fish and Chips', 'British', 4.3, 40, 15, 25, 'Crispy battered fish with golden fried potato chips and tartar sauce', 4, '[{"name":"White Fish","amount":"600g"},{"name":"Potatoes","amount":"800g"},{"name":"Flour","amount":"200g"},{"name":"Beer","amount":"250ml"},{"name":"Eggs","amount":"2"},{"name":"Tartar Sauce","amount":"150ml"}]', '[{"step":1,"instruction":"Cut and fry potato chips"},{"step":2,"instruction":"Prepare beer batter"},{"step":3,"instruction":"Coat fish and deep fry"},{"step":4,"instruction":"Serve with chips and sauce"}]', '{"calories":550,"protein":"28g","carbs":"45g","fat":"28g"}'),
('Beef Stir Fry', 'Chinese', 4.6, 25, 10, 15, 'Tender beef strips with colorful vegetables in a savory sauce over rice', 4, '[{"name":"Beef Sirloin","amount":"500g"},{"name":"Bell Peppers","amount":"2"},{"name":"Broccoli","amount":"300g"},{"name":"Soy Sauce","amount":"3 tbsp"},{"name":"Garlic","amount":"4 cloves"},{"name":"Ginger","amount":"1 inch"}]', '[{"step":1,"instruction":"Slice beef and marinate"},{"step":2,"instruction":"Chop vegetables"},{"step":3,"instruction":"Heat wok until very hot"},{"step":4,"instruction":"Cook beef and vegetables in batches"},{"step":5,"instruction":"Combine with sauce"}]', '{"calories":380,"protein":"32g","carbs":"22g","fat":"18g"}'),
('Margherita Pizza', 'Italian', 4.5, 35, 15, 20, 'Classic pizza with fresh mozzarella, basil, and tomato sauce', 4, '[{"name":"Pizza Dough","amount":"500g"},{"name":"Tomato Sauce","amount":"200ml"},{"name":"Mozzarella","amount":"300g"},{"name":"Fresh Basil","amount":"20g"},{"name":"Olive Oil","amount":"2 tbsp"}]', '[{"step":1,"instruction":"Shape dough into circle"},{"step":2,"instruction":"Spread tomato sauce"},{"step":3,"instruction":"Add torn mozzarella"},{"step":4,"instruction":"Bake at 220°C for 15 minutes"},{"step":5,"instruction":"Top with fresh basil"}]', '{"calories":480,"protein":"16g","carbs":"58g","fat":"20g"}'),
('Tom Yum Soup', 'Thai', 4.6, 30, 10, 20, 'Hot and sour soup with shrimp, mushrooms, and aromatic Thai spices', 4, '[{"name":"Shrimp","amount":"300g"},{"name":"Mushrooms","amount":"250g"},{"name":"Lemongrass","amount":"2 stalks"},{"name":"Coconut Milk","amount":"400ml"},{"name":"Lime Juice","amount":"3 tbsp"},{"name":"Chili","amount":"2"}]', '[{"step":1,"instruction":"Simmer broth with lemongrass"},{"step":2,"instruction":"Add mushrooms and shrimp"},{"step":3,"instruction":"Add coconut milk"},{"step":4,"instruction":"Season with lime and chili"},{"step":5,"instruction":"Simmer until shrimp cooked"}]', '{"calories":280,"protein":"18g","carbs":"12g","fat":"18g"}'),
('Lasagna Bolognese', 'Italian', 4.7, 90, 20, 70, 'Layered pasta with rich meat sauce and creamy béchamel sauce', 8, '[{"name":"Lasagna Sheets","amount":"400g"},{"name":"Ground Beef","amount":"500g"},{"name":"Tomatoes","amount":"800g"},{"name":"Milk","amount":"500ml"},{"name":"Butter","amount":"50g"},{"name":"Flour","amount":"50g"}]', '[{"step":1,"instruction":"Prepare bolognese sauce"},{"step":2,"instruction":"Make béchamel sauce"},{"step":3,"instruction":"Layer pasta, meat, and béchamel"},{"step":4,"instruction":"Bake at 180°C for 45 minutes"},{"step":5,"instruction":"Rest before serving"}]', '{"calories":520,"protein":"28g","carbs":"48g","fat":"22g"}'),
('Sushi Rolls', 'Japanese', 4.8, 40, 35, 5, 'Fresh sushi rice rolled with cucumber, avocado, salmon, and topped with sesame seeds', 4, '[{"name":"Sushi Rice","amount":"300g"},{"name":"Salmon","amount":"200g"},{"name":"Cucumber","amount":"1"},{"name":"Avocado","amount":"1"},{"name":"Nori","amount":"6 sheets"},{"name":"Sesame Seeds","amount":"50g"}]', '[{"step":1,"instruction":"Prepare sushi rice"},{"step":2,"instruction":"Cook rice"},{"step":3,"instruction":"Place nori on mat"},{"step":4,"instruction":"Add rice and fillings"},{"step":5,"instruction":"Roll tightly and slice"},{"step":6,"instruction":"Top with sesame"}]', '{"calories":320,"protein":"16g","carbs":"38g","fat":"12g"}'),
('Beef Bourguignon', 'French', 4.7, 180, 20, 160, 'Tender beef braised in red wine with mushrooms, onions, and herbs', 6, '[{"name":"Beef Chuck","amount":"1.5kg"},{"name":"Red Wine","amount":"750ml"},{"name":"Mushrooms","amount":"400g"},{"name":"Onions","amount":"4"},{"name":"Carrots","amount":"4"},{"name":"Beef Stock","amount":"500ml"}]', '[{"step":1,"instruction":"Brown beef pieces"},{"step":2,"instruction":"Sauté vegetables"},{"step":3,"instruction":"Add wine and stock"},{"step":4,"instruction":"Braise at 160°C for 2.5 hours"},{"step":5,"instruction":"Add mushrooms in last 30 minutes"},{"step":6,"instruction":"Serve with crusty bread"}]', '{"calories":480,"protein":"38g","carbs":"18g","fat":"26g"}'),
('Green Curry', 'Thai', 4.6, 30, 10, 20, 'Creamy green curry with chicken, bell peppers, and aromatic spices', 4, '[{"name":"Chicken Breast","amount":"600g"},{"name":"Coconut Milk","amount":"400ml"},{"name":"Green Curry Paste","amount":"3 tbsp"},{"name":"Bell Peppers","amount":"2"},{"name":"Basil","amount":"10g"},{"name":"Fish Sauce","amount":"1 tbsp"}]', '[{"step":1,"instruction":"Heat coconut milk"},{"step":2,"instruction":"Add curry paste"},{"step":3,"instruction":"Add chicken pieces"},{"step":4,"instruction":"Add peppers and simmer"},{"step":5,"instruction":"Season with fish sauce and basil"}]', '{"calories":360,"protein":"32g","carbs":"12g","fat":"20g"}'),
('Moussaka', 'Greek', 4.5, 75, 20, 55, 'Layered eggplant and meat sauce with creamy béchamel topping', 6, '[{"name":"Eggplants","amount":"2 large"},{"name":"Ground Lamb","amount":"500g"},{"name":"Tomatoes","amount":"800g"},{"name":"Milk","amount":"500ml"},{"name":"Butter","amount":"50g"},{"name":"Cinnamon","amount":"1 tsp"}]', '[{"step":1,"instruction":"Slice and fry eggplants"},{"step":2,"instruction":"Prepare meat sauce with cinnamon"},{"step":3,"instruction":"Make béchamel"},{"step":4,"instruction":"Layer eggplant and sauce"},{"step":5,"instruction":"Top with béchamel"},{"step":6,"instruction":"Bake at 180°C for 45 minutes"}]', '{"calories":450,"protein":"26g","carbs":"32g","fat":"24g"}'),
('Tacos al Pastor', 'Mexican', 4.6, 40, 20, 20, 'Marinated pork with pineapple, onions, and cilantro in warm tortillas', 4, '[{"name":"Pork Shoulder","amount":"800g"},{"name":"Pineapple","amount":"200g"},{"name":"Onions","amount":"3"},{"name":"Cilantro","amount":"30g"},{"name":"Tortillas","amount":"12"},{"name":"Lime","amount":"2"}]', '[{"step":1,"instruction":"Marinate pork in spices"},{"step":2,"instruction":"Roast pork until tender"},{"step":3,"instruction":"Slice meat"},{"step":4,"instruction":"Heat with pineapple"},{"step":5,"instruction":"Serve in warm tortillas"},{"step":6,"instruction":"Top with onions and cilantro"}]', '{"calories":420,"protein":"32g","carbs":"28g","fat":"20g"}'),
('Bouillabaisse', 'French', 4.7, 60, 20, 40, 'Traditional Provençal fish stew with saffron and fennel', 4, '[{"name":"Mixed Fish","amount":"1kg"},{"name":"Shellfish","amount":"400g"},{"name":"Onions","amount":"2"},{"name":"Fennel","amount":"1 bulb"},{"name":"Saffron","amount":"0.1g"},{"name":"Garlic","amount":"6 cloves"}]', '[{"step":1,"instruction":"Sauté aromatics"},{"step":2,"instruction":"Add fish stock"},{"step":3,"instruction":"Add saffron and fennel"},{"step":4,"instruction":"Add fish and shellfish"},{"step":5,"instruction":"Simmer until cooked"},{"step":6,"instruction":"Serve with rouille and bread"}]', '{"calories":380,"protein":"42g","carbs":"18g","fat":"16g"}'),
('Chiles Rellenos', 'Mexican', 4.4, 45, 20, 25, 'Roasted poblano peppers filled with cheese and topped with tomato sauce', 4, '[{"name":"Poblano Peppers","amount":"4"},{"name":"Oaxaca Cheese","amount":"200g"},{"name":"Eggs","amount":"6"},{"name":"Tomato Sauce","amount":"400ml"},{"name":"Onion","amount":"1"},{"name":"Oil","amount":"2 tbsp"}]', '[{"step":1,"instruction":"Roast and peel peppers"},{"step":2,"instruction":"Stuff with cheese"},{"step":3,"instruction":"Beat eggs into meringue"},{"step":4,"instruction":"Coat peppers in egg"},{"step":5,"instruction":"Fry until golden"},{"step":6,"instruction":"Serve with sauce"}]', '{"calories":380,"protein":"18g","carbs":"22g","fat":"28g"}'),
('Ramen', 'Japanese', 4.7, 120, 30, 90, 'Noodle soup with rich broth, soft-boiled eggs, and tender chashu pork', 2, '[{"name":"Ramen Noodles","amount":"300g"},{"name":"Pork Bone Broth","amount":"1L"},{"name":"Pork Belly","amount":"400g"},{"name":"Eggs","amount":"2"},{"name":"Green Onions","amount":"2"},{"name":"Bamboo Shoots","amount":"100g"}]', '[{"step":1,"instruction":"Simmer broth for hours"},{"step":2,"instruction":"Braise pork belly"},{"step":3,"instruction":"Soft boil eggs"},{"step":4,"instruction":"Cook ramen noodles"},{"step":5,"instruction":"Assemble bowl with toppings"},{"step":6,"instruction":"Pour hot broth"}]', '{"calories":580,"protein":"35g","carbs":"52g","fat":"26g"}'),
('Ceviche', 'Peruvian', 4.5, 25, 25, 0, 'Fresh fish cured in lime juice with onions, cilantro, and chili peppers', 4, '[{"name":"White Fish","amount":"600g"},{"name":"Lime Juice","amount":"6 limes"},{"name":"Red Onion","amount":"1"},{"name":"Cilantro","amount":"30g"},{"name":"Chili Pepper","amount":"2"},{"name":"Avocado","amount":"1"}]', '[{"step":1,"instruction":"Cut fish into cubes"},{"step":2,"instruction":"Marinate in lime juice"},{"step":3,"instruction":"Dice onions and peppers"},{"step":4,"instruction":"Combine after 10 minutes"},{"step":5,"instruction":"Serve with avocado"},{"step":6,"instruction":"Garnish with cilantro"}]', '{"calories":280,"protein":"35g","carbs":"12g","fat":"8g"}')
ON CONFLICT DO NOTHING;
